# Generated by Django 4.2.3 on 2023-09-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SE", "0002_journal_journalauthor_alter_report_publish_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="dl_path",
            field=models.TextField(max_length=191, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="path",
            field=models.TextField(max_length=191, unique=True),
        ),
    ]
