# Generated by Django 4.2.3 on 2023-09-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SE", "0003_alter_report_dl_path_alter_report_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="pub_status",
        ),
    ]
