# Generated by Django 4.2.3 on 2023-09-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SE", "0006_remove_journalarticle_pub_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("test1", models.CharField(max_length=3, null=True)),
                ("test2", models.CharField(max_length=3, null=True, unique=True)),
            ],
        ),
    ]
