# Generated by Django 4.2.3 on 2023-09-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SE", "0009_remove_journalarticle_authors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalArticle",
            fields=[
                ("web_url", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("title", models.TextField(null=True)),
                ("title_fa", models.TextField(null=True)),
                ("content_type", models.CharField(max_length=30, null=True)),
                ("content_type_fa", models.CharField(max_length=30, null=True)),
                ("publish_type", models.CharField(max_length=15, null=True)),
                ("gregorian_pubdate_day", models.CharField(max_length=2, null=True)),
                ("gregorian_pubdate_month", models.CharField(max_length=2, null=True)),
                ("gregorian_pubdate_year", models.CharField(max_length=4, null=True)),
                ("subject", models.CharField(max_length=40, null=True)),
                ("subject_fa", models.CharField(max_length=40, null=True)),
                ("language", models.CharField(max_length=10, null=True)),
                ("start_page", models.CharField(max_length=5, null=True)),
                ("end_page", models.CharField(max_length=5, null=True)),
                ("id_pii", models.CharField(max_length=20, null=True, unique=True)),
                ("id_doi", models.CharField(max_length=20, null=True, unique=True)),
                ("abstract", models.TextField(null=True)),
                ("abstract_preprocessed", models.TextField(null=True)),
                ("abstract_summary", models.TextField(null=True)),
                ("abstract_fa", models.TextField(null=True)),
                ("abstract_fa_preprocessed", models.TextField(null=True)),
                ("abstract_fa_summary", models.TextField(null=True)),
                ("authors", models.ManyToManyField(related_name="journal_article_authors", to="SE.journalauthor")),
                ("english_keywords", models.ManyToManyField(related_name="journal_english_keywords", to="SE.englishphrase")),
                ("persian_keywords", models.ManyToManyField(related_name="journal_persian_keywords", to="SE.persianphrase")),
            ],
        ),
    ]
